### ISSUE TITLE
Error while sending and confirming transactions with nodejs

### ISSUE THREAD

**Issue by kompotkot** [solana-labs/solana-program-library#1838]
Hello, during using of Solana npm module `@solana/spl-token` I faced an issue. I am not be able to confirm transactions when I am using your hardcoded `programId` for token issuing. 

Example of code I am using:

```javascript
import { Token, TOKEN_PROGRAM_ID } from '@solana/spl-token'

const myAccount = // <fetching my account from ~/.config/solana/id.json>
const connection = // <connection to devnet>

// ...
// <Some logs to be sure connection established and proper account used>
// ...

const token = await Token.createMint(
        connection,
        myAccount,
        myAccount.publicKey,
        null,
        8,
        TOKEN_PROGRAM_ID
    )
```

And I receive an error:
```bash
> solana-test@1.0.0 start
> tsc && node build/index.js

Established connection with cluster: https://api.devnet.solana.com { 'feature-set': 3533521759, 'solana-core': '1.6.10' }
Used account with public key: 3fru6kFEEJLcv2ddRGoZGz7bYVoNWDPLrPgbxAdPxSjA
Balance of 3fru6kFEEJLcv2ddRGoZGz7bYVoNWDPLrPgbxAdPxSjA = 32.99645912

Error: Signature verification failed
    at Transaction.serialize (/home/ubuntu/Documents/solana-test/node_modules/@solana/web3.js/lib/index.cjs.js:1105:13)
    at Connection.sendTransaction (/home/ubuntu/Documents/solana-test/node_modules/@solana/web3.js/lib/index.cjs.js:4587:41)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Object.sendAndConfirmTransaction (/home/ubuntu/Documents/solana-test/node_modules/@solana/web3.js/lib/index.cjs.js:1249:21)
    at async createToken (/home/ubuntu/Documents/solana-test/build/index.js:58:5)
    at async main (/home/ubuntu/Documents/solana-test/build/index.js:152:19)
```

After some investigation I figured out, that code failed inside function `Token.createMint()` on step `sendAndConfirmTransaction()`.

**Comment by willemmcd** [comment]
I'm having a similar issue on createMint(..) with a React app using phantom wallet as the provider. Have you managed to sort out your issue?

**Comment by michalko** [comment]
same, does anyody know how do i createMint on mainNet? i am connected to Phantom wallet using @solana/wallet-adapter-react, but it doesn't have access to privateKey, so i can't use createMint, because it needs Signer which has a secretKey

**Comment by t-nelson** [comment]
Please come to https://solana.com/discord.  We don't use github for user support
