### ISSUE TITLE
run `test_cross_program_invocation` failed

### ISSUE THREAD

**Issue by 3for** [solana-labs/solana-program-library#2369]
$ cargo test test_cross_program_invocation --no-default-features --features "test-bpf"

get error info:
```
test test_cross_program_invocation has been running for over 60 seconds
test test_cross_program_invocation ... FAILED

failures:

---- test_cross_program_invocation stdout ----
thread 'solana-bank-forks-client' panicked at 'Account data resizing not supported yet: 0 -> 42. Consider making this test conditional on `#[cfg(feature = "test-bpf")]`', /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/solana-program-test-1.7.11/src/lib.rs:357:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'test_cross_program_invocation' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: TimedOut, error: "Client dropped expired request." })', examples/rust/cross-program-invocation/tests/functional.rs:49:57
```

1) How can I fix this problem?
2) Any other example for cross program invocation?

**Comment by 3for** [comment]
Thanks a lot. It fixed.
