### ISSUE TITLE
    Create Account: account Address { address: DHu7SnA9Xr8zWgTz898J31njRaLUX1bM9ve2ya8xJKbp, base: None } already in use     

### ISSUE THREAD

**Issue by Poonamsingh080** [solana-labs/solana-program-library#2677]
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0 
    Program 11111111111111111111111111111111 invoke [1]
    Create Account: account Address { address: DHu7SnA9Xr8zWgTz898J31njRaLUX1bM9ve2ya8xJKbp, base: None } already in use
    Program 11111111111111111111111111111111 failed: custom program error: 0x0
SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0
    at Connection.sendEncodedTransaction (/home/poonam/Desktop/token-swap/soldex-token-swap-SC/token-swap/js/node_modules/@solana/web3.js/src/connection.ts:3668:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Connection.sendRawTransaction (/home/poonam/Desktop/token-swap/soldex-token-swap-SC/token-swap/js/node_modules/@solana/web3.js/src/connection.ts:3628:20)
    at async Connection.sendTransaction (/home/poonam/Desktop/token-swap/soldex-token-swap-SC/token-swap/js/node_modules/@solana/web3.js/src/connection.ts:3616:12)
    at async sendAndConfirmTransaction (/home/poonam/Desktop/token-swap/soldex-token-swap-SC/token-swap/js/node_modules/@solana/web3.js/src/util/send-and-confirm-transaction.ts:29:21)
    at async Function.createTokenSwap (/home/poonam/Desktop/token-swap/soldex-token-swap-SC/token-swap/js/src/index.ts:432:5)
    at async createTokenSwap (/home/poonam/Desktop/token-swap/soldex-token-swap-SC/token-swap/js/cli/token-swap-script.ts:248:15)
    at async main (/home/poonam/Desktop/token-swap/soldex-token-swap-SC/token-swap/js/cli/script-main.ts:15:5) {
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Create Account: account Address { address: DHu7SnA9Xr8zWgTz898J31njRaLUX1bM9ve2ya8xJKbp, base: None } already in use',
    'Program 11111111111111111111111111111111 failed: custom program error: 0x0'
  ]
}

**Comment by joncinque** [comment]
Hi there, GitHub isn't so useful for developer support, so we invite you to join us in our Discord: https://discord.gg/NdkkHZvh then you can ask questions in the #developer-support channel.

As for your error, looks like the account you're trying to create is already created / allocated. Since the account has already been assigned to a program, it cannot be recreated again.  You can read through more info at: https://docs.solana.com/developing/programming-model/accounts#creating
