### ISSUE TITLE
stake-pool-js: Browser build not available

### ISSUE THREAD

**Issue by CMEONE** [solana-labs/solana-program-library#2688]
Hello again @joncinque nice to see #2681 solving a lot of the issues I was getting with building! Right now, I'm trying to use browserify to build the stake-pool JS bindings for the browser and am running into some errors, I was wondering if you had any specific intentions on how to build the bindings for the browser.

I tried running: `browserify index.js -o bundle.js -s StakePool` but ran into the following error:

```
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0) while parsing /redacted/solana-program-library/stake-pool/js/node_modules/@solana/web3.js/lib/index.browser.esm.js while parsing file: /redacted/solana-program-library/stake-pool/js/node_modules/@solana/web3.js/lib/index.browser.esm.js
    at DestroyableTransform.end [as _flush] (~/.nvm/versions/node/v15.1.0/lib/node_modules/browserify/node_modules/insert-module-globals/index.js:114:21)
    at DestroyableTransform.prefinish (~/.nvm/versions/node/v15.1.0/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at DestroyableTransform.emit (node:events:327:20)
    at prefinish (~/.nvm/versions/node/v15.1.0/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (~/.nvm/versions/node/v15.1.0/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (~/.nvm/versions/node/v15.1.0/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (~/.nvm/versions/node/v15.1.0/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DestroyableTransform.onend (~/.nvm/versions/node/v15.1.0/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (node:events:433:28)
    at DestroyableTransform.emit (node:events:339:22)
```

It seems that the esm version of `@solana/web3.js` is being used which is causing errors, is there any reasoning for why the esm version of the module is being pulled instead of a built cjs version?

P.S. the stake pool I'm building is at [stake.solblaze.org](https://stake.solblaze.org/) in case you're interested.

**Comment by joncinque** [comment]
Oops, I should've asked if you were building for browser.  I'll get to this next week.  In the meantime, you can fork the repo and build it yourself using a tsconfig.browser.json like the token-swap one: https://github.com/solana-labs/solana-program-library/blob/master/token-swap/js/tsconfig.browser.json

**Comment by CMEONE** [comment]
Just added the `tsconfig.browser.json` and the appropriate scripts, but I'm still having issues running it in the browser. I can't just do `<script type="module">...</script>` since `@solana/web3.js` is imported. I've tried to bundle using `webpack` default command (`npx webpack`) but am also running into errors like this:

```
.js
        Field 'browser' doesn't contain a valid alias configuration
        /redacted/solana-program-library/stake-pool/js/src.js doesn't exist
```

For reference, I added `"browser": "dist.browser/index.js"` to the `package.json` file. 

I'm probably just missing something super simple since I don't use bundlers with ECMAScript modules that often, but it would be helpful if you could please provide some guidance as to how to build a standalone bundled file that can be imported into my existing client-side code through a script tag or within a `<script type="module">...</script>` block.

I'm happy to make a PR with my browser support changes (`package.json`, `tsconfig.browser.json`, etc.) once I can get the browser build working. Thanks again for all of your help and patience!

**Comment by joncinque** [comment]
I looked into this a bit, and your best bet will be to add some rollup-like configuration if you want a full browser bundle.  I copy-pasted the solana/web3.js rollup https://github.com/solana-labs/solana/blob/master/web3.js/rollup.config.js into stake-pool/js for a local test, and got it to work out in browser.  You'll probably want to do something more clever than that, but that'll at least get you working!  If you want to submit a PR for the bundling, I'll be happy to review :smile:
