### ISSUE TITLE
@solana/spl-token: TypeScript error with TOKEN_PROGRAM_ID

### ISSUE THREAD

**Issue by joxoby** [solana-labs/solana-program-library#2934]
The code
```javascript
import { TOKEN_PROGRAM_ID } from "@solana/spl-token";
...
console.log(TOKEN_PROGRAM_ID);
```
results in error
```
Layout.ts:1107 Uncaught TypeError: fields must be array of Layout instances
    at new Structure (Layout.ts:1107:1)
    at exports.struct (Layout.ts:2614:1)
    at Module../node_modules/@solana/spl-token/lib/esm/instructions/initializeMint.mjs (initializeMint.ts:23:1)
    at Module.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at Module../node_modules/@solana/spl-token/lib/esm/instructions/index.mjs (freezeAccount.ts:140:1)
    at Module.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
```
I found this very strange. Any ideas?

**Comment by joxoby** [comment]
Interestingly, inserting the public key directly instead of using the constant `TOKEN_PROGRAM_ID`, that is:
```javascript
 // Get the list of tokens for the current wallet
  const getTokens = async () => {
    const accounts = await connection.getParsedTokenAccountsByOwner(
      publicKey as PublicKey,
      {
        programId: new PublicKey("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
      }
    );
```
solves the issue.

**Comment by joxoby** [comment]
Solution here: https://docs.jup.ag/notes/troubleshooting-issues
