### ISSUE TITLE
create multisig: "TypeError: Cannot read properties of undefined (reading 'toString')"

### ISSUE THREAD

**Issue by arivictor** [solana-labs/solana-program-library#3021]
Hi,

Following the documentation on creating a multisig account, https://spl.solana.com/token#multisig-usage

I am facing an error at the part that actually calls the `spl-token` packages `createMultisig` function:

```javascript
const multisigKey = await spl.createMultisig(
    connection,
    payer,
    [
        signer1.publicKey,
        signer2.publicKey,
        signer3.publicKey
    ],
    2
);
console.log(`Created 2/3 multisig ${multisigKey.toBase58()}`);
```
It throws an error in the spl-token package:

```shell
~/node_modules/@solana/web3.js/lib/index.cjs.js:2686
      const key = signer.publicKey.toString();
                                   ^
TypeError: Cannot read properties of undefined (reading 'toString')
    at Transaction.sign (/Users/ari/WebstormProjects/solanatesting/node_modules/@solana/web3.js/lib/index.cjs.js:2686:36)
    at Connection.sendTransaction (/Users/ari/WebstormProjects/solanatesting/node_modules/@solana/web3.js/lib/index.cjs.js:6736:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async sendAndConfirmTransaction (/Users/ari/WebstormProjects/solanatesting/node_modules/@solana/web3.js/lib/index.cjs.js:2976:21)
```

# How to reproduce

* Package: `"@solana/spl-token": "^0.2.0"`
* Node: `v16.11.1`

Script:

```javascript
// index.js

const spl = require("@solana/spl-token");
const web3 = require("@solana/web3.js");

(async () => {

    const connection = new web3.Connection(web3.clusterApiUrl('devnet'), 'confirmed');

    const payer = new web3.PublicKey("5XkZJg5fEGh1pjvKnX44cL7HygW6ZF1RtpD6R5kVEDCn");
    const signer1 = web3.Keypair.generate();
    const signer2 = web3.Keypair.generate();
    const signer3 = web3.Keypair.generate();

    const multisigKey = await spl.createMultisig(
        connection,
        payer,
        [
            signer1.publicKey,
            signer2.publicKey,
            signer3.publicKey
        ],
        2
    );

    console.log(`Created 2/3 multisig ${multisigKey.toBase58()}`);

})();
```

then run:

```shell
$ node index.js
```

The above key is the dummy account I setup with some airdropped sol.

**Comment by arivictor** [comment]
I realised my error.

I can't use `new PublicKey()`. I instead need to load the key from the secret key:

```javascript
let secretKey = Uint8Array.from([ // secret key value ]);
let payer = web3.Keypair.fromSecretKey(secretKey);
```

**Comment by arivictor** [comment]
ref: https://docs.solana.com/developing/clients/javascript-api#connecting-to-a-wallet

**Comment by jordansexton** [comment]
Thanks for sharing the solution! It's worth noting you can avoid this by using TypeScript 😄 Passing `PublicKey` where `Signer` is expected should result in a descriptive compile-time error.
