### ISSUE TITLE
Error with `init` Account

### ISSUE THREAD

**Issue by dev-tom-0108** [solana-labs/solana-program-library#3320]
I was creating auction project but I got an error.
```js
#[derive(Accounts)]
#[instruction(
    bump: u8,
    title: String,
    floor: u64,
    increment: u64,
    start_time: u64,
    end_time: u64,
    bidder_cap: u64,
    token_amount: u64
)]
pub struct CreateOpenAuction<'info> {
    #[account(init,
        seeds=[b"open auction", owner.to_account_info().key.as_ref(), name_seed(&title)],
        bump = bump,
        payer = owner,
        space = OpenAuction::LEN +
        VECTOR_LENGTH_PREFIX + (bidder_cap as usize)*PUBLIC_KEY_LENGTH +
        VECTOR_LENGTH_PREFIX + (bidder_cap as usize)*U64_LENGTH +
        VECTOR_LENGTH_PREFIX + (bidder_cap as usize)*U64_LENGTH)]
    pub auction: Account<'info, OpenAuction>,
    #[account(mut)]
    pub auction_ata: AccountInfo<'info>,
    ...
```
in script code
```js
const [auctionAddress, bump] = await PublicKey.findProgramAddress(
      [Buffer.from("open auction"), owner.toBytes(), Buffer.from(auctionTitle.slice(0, 32))],
      program.programId
  );
const tx = await program.rpc.createOpenAuction(new anchor.BN(bump),
      auctionTitle,
      new anchor.BN(floor * DECIMALS),
      new anchor.BN(tokenFloor * DECIMALS),
      new anchor.BN(increment * DECIMALS),
      new anchor.BN(tokenIncrement * DECIMALS),
      new anchor.BN(startTime),
      new anchor.BN(endTime),
      new anchor.BN(biddercap),
      new anchor.BN(amount), {
      accounts: {
          auction: auctionAddress,
          auctionAta: auctionAta,
          auctionTokenAta,
          owner,
          ownerAta,
          mint: nft_mint,
          tokenMint,
          tokenProgram: TOKEN_PROGRAM_ID,
          ataProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rentSysvar: SYSVAR_RENT_PUBKEY,
      },
      signers: [],
  });
```
I got this error:
```ps
Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x3
    at Connection.sendEncodedTransaction (/home/ubuntu/apollo/auction-program/auction/node_modules/@solana/web3.js/src/connection.ts:4052:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Connection.sendRawTransaction (/home/ubuntu/apollo/auction-program/auction/node_modules/@solana/web3.js/src/connection.ts:4014:20)
    at sendAndConfirmRawTransaction (/home/ubuntu/apollo/auction-program/auction/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at Provider.send (/home/ubuntu/apollo/auction-program/auction/node_modules/@project-serum/anchor/src/provider.ts:118:18)
    at Object.rpc [as createOpenAuction] (/home/ubuntu/apollo/auction-program/auction/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:25:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by acheroncrypto** [comment]
This is not the place to ask for Anchor support, you should ask in [Anchor Discord](http://discord.gg/ZCHmqvXgDw)

**Comment by joncinque** [comment]
Indeed, thanks @acheroncrypto !
