### ISSUE TITLE
@solana/spl-token-group Function Missing  

### ISSUE THREAD

**Issue by monar24** [solana-labs/solana-program-library#7444]
Hi, 

I am getting the following error in my node app. 
Is there a function missing from spl-token-group? 

I am using the following version of spl-token
"@solana/spl-token": "^0.4.9",

My code worked previously on ^0.4.8. I am wondering why this is appearing now. I tried downgrading but encountered the same issue. I noticed my old code also ran spl-token-group 0.0.5 instead of 0.0.7 but downgrading that in addition did not work.

I have this running in a basic react app for context and have attempted to use a config-override as well. 
I have typescript code (sdk) that uses spl-token functions within my business logic and I import it into my react app by linking the package (yarn link)

**Here is my import statement in my class:** 
```
import { TOKEN_PROGRAM_ID, ASSOCIATED_TOKEN_PROGRAM_ID, getAssociatedTokenAddress, createAssociatedTokenAccountInstruction, createTransferInstruction, getAccount } from '@solana/spl-token';
```

**Here's an example utility method:**

```
    async getUSDCTokenAccount(publicKey: PublicKey): Promise<PublicKey> {
        return await getAssociatedTokenAddress(
            this.USDC_MINT,
            publicKey,
            true,
            TOKEN_PROGRAM_ID,
            ASSOCIATED_TOKEN_PROGRAM_ID
        );
    }
```

**Error displayed on frontend UI:** 
```
ERROR
(0 , codecs_1.getBytesCodec) is not a function
TypeError: (0 , codecs_1.getBytesCodec) is not a function
    at ../../Documents/dev/payments-sdk-node/node_modules/@solana/spl-token-group/lib/cjs/state/tokenGroup.js (http://localhost:3000/static/js/bundle.js:65017:129)
    at options.factory (http://localhost:3000/static/js/bundle.js:84369:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:83799:32)
    at fn (http://localhost:3000/static/js/bundle.js:84028:21)
    at ../../Documents/dev/payments-sdk-node/node_modules/@solana/spl-token-group/lib/cjs/state/index.js (http://localhost:3000/static/js/bundle.js:64995:14)
    at options.factory (http://localhost:3000/static/js/bundle.js:84369:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:83799:32)
    at fn (http://localhost:3000/static/js/bundle.js:84028:21)
    at ../../Documents/dev/payments-sdk-node/node_modules/@solana/spl-token-group/lib/cjs/index.js (http://localhost:3000/static/js/bundle.js:64817:14)
    at options.factory (http://localhost:3000/static/js/bundle.js:84369:31)
```

**Comment by joncinque** [comment]
@steveluscher do you know anything about this? It looks like you published 0.4.9

**Comment by steveluscher** [comment]
Strange; I'm not able to repro this: https://codesandbox.io/p/sandbox/dt8wzw

What does your lockfile look like, @monar24?

**Comment by monar24** [comment]
Hi, 

I resolved it by moving my code to our backend. It threw the error in my sdk when I tried to invoke from the frontend, but calling it from the backend did not throw the error.  Works for my use case now. Safe to close this issue, thank you very much for your time!
